# Generated by Django 4.1.7 on 2023-03-10 11:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24)),
                ('password', models.CharField(max_length=24)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
            options={
                'db_table': 'custom',
            },
        ),
    ]
